// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hmi_3d/mv_od.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_hmi_5f3d_2fmv_5fod_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_hmi_5f3d_2fmv_5fod_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_hmi_5f3d_2fmv_5fod_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_hmi_5f3d_2fmv_5fod_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[4]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_hmi_5f3d_2fmv_5fod_2eproto;
class PB_AVAP_DynBarrier;
class PB_AVAP_DynBarrierDefaultTypeInternal;
extern PB_AVAP_DynBarrierDefaultTypeInternal _PB_AVAP_DynBarrier_default_instance_;
class PB_AVAP_Speedbump;
class PB_AVAP_SpeedbumpDefaultTypeInternal;
extern PB_AVAP_SpeedbumpDefaultTypeInternal _PB_AVAP_Speedbump_default_instance_;
class PB_AVAP_StcBarrier;
class PB_AVAP_StcBarrierDefaultTypeInternal;
extern PB_AVAP_StcBarrierDefaultTypeInternal _PB_AVAP_StcBarrier_default_instance_;
class PB_OdInfo;
class PB_OdInfoDefaultTypeInternal;
extern PB_OdInfoDefaultTypeInternal _PB_OdInfo_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::PB_AVAP_DynBarrier* Arena::CreateMaybeMessage<::PB_AVAP_DynBarrier>(Arena*);
template<> ::PB_AVAP_Speedbump* Arena::CreateMaybeMessage<::PB_AVAP_Speedbump>(Arena*);
template<> ::PB_AVAP_StcBarrier* Arena::CreateMaybeMessage<::PB_AVAP_StcBarrier>(Arena*);
template<> ::PB_OdInfo* Arena::CreateMaybeMessage<::PB_OdInfo>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class PB_AVAP_StcBarrier PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PB_AVAP_StcBarrier) */ {
 public:
  inline PB_AVAP_StcBarrier() : PB_AVAP_StcBarrier(nullptr) {};
  virtual ~PB_AVAP_StcBarrier();

  PB_AVAP_StcBarrier(const PB_AVAP_StcBarrier& from);
  PB_AVAP_StcBarrier(PB_AVAP_StcBarrier&& from) noexcept
    : PB_AVAP_StcBarrier() {
    *this = ::std::move(from);
  }

  inline PB_AVAP_StcBarrier& operator=(const PB_AVAP_StcBarrier& from) {
    CopyFrom(from);
    return *this;
  }
  inline PB_AVAP_StcBarrier& operator=(PB_AVAP_StcBarrier&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const PB_AVAP_StcBarrier& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PB_AVAP_StcBarrier* internal_default_instance() {
    return reinterpret_cast<const PB_AVAP_StcBarrier*>(
               &_PB_AVAP_StcBarrier_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(PB_AVAP_StcBarrier& a, PB_AVAP_StcBarrier& b) {
    a.Swap(&b);
  }
  inline void Swap(PB_AVAP_StcBarrier* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PB_AVAP_StcBarrier* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PB_AVAP_StcBarrier* New() const final {
    return CreateMaybeMessage<PB_AVAP_StcBarrier>(nullptr);
  }

  PB_AVAP_StcBarrier* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PB_AVAP_StcBarrier>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const PB_AVAP_StcBarrier& from);
  void MergeFrom(const PB_AVAP_StcBarrier& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PB_AVAP_StcBarrier* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PB_AVAP_StcBarrier";
  }
  protected:
  explicit PB_AVAP_StcBarrier(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_hmi_5f3d_2fmv_5fod_2eproto);
    return ::descriptor_table_hmi_5f3d_2fmv_5fod_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAVAPStcBarrierTypeFieldNumber = 1,
    kAVAPStcBarrierXFieldNumber = 2,
    kAVAPStcBarrierYFieldNumber = 3,
    kAVAPStcBarrierDrctFieldNumber = 4,
  };
  // uint32 AVAP_StcBarrierType = 1;
  void clear_avap_stcbarriertype();
  ::PROTOBUF_NAMESPACE_ID::uint32 avap_stcbarriertype() const;
  void set_avap_stcbarriertype(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_avap_stcbarriertype() const;
  void _internal_set_avap_stcbarriertype(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // float AVAP_StcBarrier_X = 2;
  void clear_avap_stcbarrier_x();
  float avap_stcbarrier_x() const;
  void set_avap_stcbarrier_x(float value);
  private:
  float _internal_avap_stcbarrier_x() const;
  void _internal_set_avap_stcbarrier_x(float value);
  public:

  // float AVAP_StcBarrier_Y = 3;
  void clear_avap_stcbarrier_y();
  float avap_stcbarrier_y() const;
  void set_avap_stcbarrier_y(float value);
  private:
  float _internal_avap_stcbarrier_y() const;
  void _internal_set_avap_stcbarrier_y(float value);
  public:

  // uint32 AVAP_StcBarrierDrct = 4;
  void clear_avap_stcbarrierdrct();
  ::PROTOBUF_NAMESPACE_ID::uint32 avap_stcbarrierdrct() const;
  void set_avap_stcbarrierdrct(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_avap_stcbarrierdrct() const;
  void _internal_set_avap_stcbarrierdrct(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:PB_AVAP_StcBarrier)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::uint32 avap_stcbarriertype_;
  float avap_stcbarrier_x_;
  float avap_stcbarrier_y_;
  ::PROTOBUF_NAMESPACE_ID::uint32 avap_stcbarrierdrct_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_hmi_5f3d_2fmv_5fod_2eproto;
};
// -------------------------------------------------------------------

class PB_AVAP_DynBarrier PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PB_AVAP_DynBarrier) */ {
 public:
  inline PB_AVAP_DynBarrier() : PB_AVAP_DynBarrier(nullptr) {};
  virtual ~PB_AVAP_DynBarrier();

  PB_AVAP_DynBarrier(const PB_AVAP_DynBarrier& from);
  PB_AVAP_DynBarrier(PB_AVAP_DynBarrier&& from) noexcept
    : PB_AVAP_DynBarrier() {
    *this = ::std::move(from);
  }

  inline PB_AVAP_DynBarrier& operator=(const PB_AVAP_DynBarrier& from) {
    CopyFrom(from);
    return *this;
  }
  inline PB_AVAP_DynBarrier& operator=(PB_AVAP_DynBarrier&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const PB_AVAP_DynBarrier& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PB_AVAP_DynBarrier* internal_default_instance() {
    return reinterpret_cast<const PB_AVAP_DynBarrier*>(
               &_PB_AVAP_DynBarrier_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(PB_AVAP_DynBarrier& a, PB_AVAP_DynBarrier& b) {
    a.Swap(&b);
  }
  inline void Swap(PB_AVAP_DynBarrier* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PB_AVAP_DynBarrier* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PB_AVAP_DynBarrier* New() const final {
    return CreateMaybeMessage<PB_AVAP_DynBarrier>(nullptr);
  }

  PB_AVAP_DynBarrier* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PB_AVAP_DynBarrier>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const PB_AVAP_DynBarrier& from);
  void MergeFrom(const PB_AVAP_DynBarrier& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PB_AVAP_DynBarrier* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PB_AVAP_DynBarrier";
  }
  protected:
  explicit PB_AVAP_DynBarrier(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_hmi_5f3d_2fmv_5fod_2eproto);
    return ::descriptor_table_hmi_5f3d_2fmv_5fod_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAVAPDynBarrierTypeFieldNumber = 1,
    kAVAPDynBarrierXFieldNumber = 2,
    kAVAPDynBarrierYFieldNumber = 3,
    kAVAPDynBarrierDrctFieldNumber = 4,
  };
  // uint32 AVAP_DynBarrierType = 1;
  void clear_avap_dynbarriertype();
  ::PROTOBUF_NAMESPACE_ID::uint32 avap_dynbarriertype() const;
  void set_avap_dynbarriertype(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_avap_dynbarriertype() const;
  void _internal_set_avap_dynbarriertype(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // float AVAP_DynBarrier_X = 2;
  void clear_avap_dynbarrier_x();
  float avap_dynbarrier_x() const;
  void set_avap_dynbarrier_x(float value);
  private:
  float _internal_avap_dynbarrier_x() const;
  void _internal_set_avap_dynbarrier_x(float value);
  public:

  // float AVAP_DynBarrier_Y = 3;
  void clear_avap_dynbarrier_y();
  float avap_dynbarrier_y() const;
  void set_avap_dynbarrier_y(float value);
  private:
  float _internal_avap_dynbarrier_y() const;
  void _internal_set_avap_dynbarrier_y(float value);
  public:

  // uint32 AVAP_DynBarrierDrct = 4;
  void clear_avap_dynbarrierdrct();
  ::PROTOBUF_NAMESPACE_ID::uint32 avap_dynbarrierdrct() const;
  void set_avap_dynbarrierdrct(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_avap_dynbarrierdrct() const;
  void _internal_set_avap_dynbarrierdrct(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:PB_AVAP_DynBarrier)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::uint32 avap_dynbarriertype_;
  float avap_dynbarrier_x_;
  float avap_dynbarrier_y_;
  ::PROTOBUF_NAMESPACE_ID::uint32 avap_dynbarrierdrct_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_hmi_5f3d_2fmv_5fod_2eproto;
};
// -------------------------------------------------------------------

class PB_AVAP_Speedbump PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PB_AVAP_Speedbump) */ {
 public:
  inline PB_AVAP_Speedbump() : PB_AVAP_Speedbump(nullptr) {};
  virtual ~PB_AVAP_Speedbump();

  PB_AVAP_Speedbump(const PB_AVAP_Speedbump& from);
  PB_AVAP_Speedbump(PB_AVAP_Speedbump&& from) noexcept
    : PB_AVAP_Speedbump() {
    *this = ::std::move(from);
  }

  inline PB_AVAP_Speedbump& operator=(const PB_AVAP_Speedbump& from) {
    CopyFrom(from);
    return *this;
  }
  inline PB_AVAP_Speedbump& operator=(PB_AVAP_Speedbump&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const PB_AVAP_Speedbump& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PB_AVAP_Speedbump* internal_default_instance() {
    return reinterpret_cast<const PB_AVAP_Speedbump*>(
               &_PB_AVAP_Speedbump_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(PB_AVAP_Speedbump& a, PB_AVAP_Speedbump& b) {
    a.Swap(&b);
  }
  inline void Swap(PB_AVAP_Speedbump* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PB_AVAP_Speedbump* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PB_AVAP_Speedbump* New() const final {
    return CreateMaybeMessage<PB_AVAP_Speedbump>(nullptr);
  }

  PB_AVAP_Speedbump* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PB_AVAP_Speedbump>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const PB_AVAP_Speedbump& from);
  void MergeFrom(const PB_AVAP_Speedbump& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PB_AVAP_Speedbump* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PB_AVAP_Speedbump";
  }
  protected:
  explicit PB_AVAP_Speedbump(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_hmi_5f3d_2fmv_5fod_2eproto);
    return ::descriptor_table_hmi_5f3d_2fmv_5fod_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAVAPSpeedbumpAXFieldNumber = 1,
    kAVAPSpeedbumpAYFieldNumber = 2,
    kAVAPSpeedbumpBXFieldNumber = 3,
    kAVAPSpeedbumpBYFieldNumber = 4,
  };
  // float AVAP_Speedbump_A_X = 1;
  void clear_avap_speedbump_a_x();
  float avap_speedbump_a_x() const;
  void set_avap_speedbump_a_x(float value);
  private:
  float _internal_avap_speedbump_a_x() const;
  void _internal_set_avap_speedbump_a_x(float value);
  public:

  // float AVAP_Speedbump_A_Y = 2;
  void clear_avap_speedbump_a_y();
  float avap_speedbump_a_y() const;
  void set_avap_speedbump_a_y(float value);
  private:
  float _internal_avap_speedbump_a_y() const;
  void _internal_set_avap_speedbump_a_y(float value);
  public:

  // float AVAP_Speedbump_B_X = 3;
  void clear_avap_speedbump_b_x();
  float avap_speedbump_b_x() const;
  void set_avap_speedbump_b_x(float value);
  private:
  float _internal_avap_speedbump_b_x() const;
  void _internal_set_avap_speedbump_b_x(float value);
  public:

  // float AVAP_Speedbump_B_Y = 4;
  void clear_avap_speedbump_b_y();
  float avap_speedbump_b_y() const;
  void set_avap_speedbump_b_y(float value);
  private:
  float _internal_avap_speedbump_b_y() const;
  void _internal_set_avap_speedbump_b_y(float value);
  public:

  // @@protoc_insertion_point(class_scope:PB_AVAP_Speedbump)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  float avap_speedbump_a_x_;
  float avap_speedbump_a_y_;
  float avap_speedbump_b_x_;
  float avap_speedbump_b_y_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_hmi_5f3d_2fmv_5fod_2eproto;
};
// -------------------------------------------------------------------

class PB_OdInfo PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PB_OdInfo) */ {
 public:
  inline PB_OdInfo() : PB_OdInfo(nullptr) {};
  virtual ~PB_OdInfo();

  PB_OdInfo(const PB_OdInfo& from);
  PB_OdInfo(PB_OdInfo&& from) noexcept
    : PB_OdInfo() {
    *this = ::std::move(from);
  }

  inline PB_OdInfo& operator=(const PB_OdInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline PB_OdInfo& operator=(PB_OdInfo&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const PB_OdInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PB_OdInfo* internal_default_instance() {
    return reinterpret_cast<const PB_OdInfo*>(
               &_PB_OdInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(PB_OdInfo& a, PB_OdInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(PB_OdInfo* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PB_OdInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PB_OdInfo* New() const final {
    return CreateMaybeMessage<PB_OdInfo>(nullptr);
  }

  PB_OdInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PB_OdInfo>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const PB_OdInfo& from);
  void MergeFrom(const PB_OdInfo& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PB_OdInfo* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PB_OdInfo";
  }
  protected:
  explicit PB_OdInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_hmi_5f3d_2fmv_5fod_2eproto);
    return ::descriptor_table_hmi_5f3d_2fmv_5fod_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAStcBarrierFieldNumber = 2,
    kADynBarrierFieldNumber = 3,
    kASpeedbumpFieldNumber = 4,
    kTimeMsecFieldNumber = 1,
  };
  // repeated .PB_AVAP_StcBarrier aStcBarrier = 2;
  int astcbarrier_size() const;
  private:
  int _internal_astcbarrier_size() const;
  public:
  void clear_astcbarrier();
  ::PB_AVAP_StcBarrier* mutable_astcbarrier(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PB_AVAP_StcBarrier >*
      mutable_astcbarrier();
  private:
  const ::PB_AVAP_StcBarrier& _internal_astcbarrier(int index) const;
  ::PB_AVAP_StcBarrier* _internal_add_astcbarrier();
  public:
  const ::PB_AVAP_StcBarrier& astcbarrier(int index) const;
  ::PB_AVAP_StcBarrier* add_astcbarrier();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PB_AVAP_StcBarrier >&
      astcbarrier() const;

  // repeated .PB_AVAP_DynBarrier aDynBarrier = 3;
  int adynbarrier_size() const;
  private:
  int _internal_adynbarrier_size() const;
  public:
  void clear_adynbarrier();
  ::PB_AVAP_DynBarrier* mutable_adynbarrier(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PB_AVAP_DynBarrier >*
      mutable_adynbarrier();
  private:
  const ::PB_AVAP_DynBarrier& _internal_adynbarrier(int index) const;
  ::PB_AVAP_DynBarrier* _internal_add_adynbarrier();
  public:
  const ::PB_AVAP_DynBarrier& adynbarrier(int index) const;
  ::PB_AVAP_DynBarrier* add_adynbarrier();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PB_AVAP_DynBarrier >&
      adynbarrier() const;

  // repeated .PB_AVAP_Speedbump aSpeedbump = 4;
  int aspeedbump_size() const;
  private:
  int _internal_aspeedbump_size() const;
  public:
  void clear_aspeedbump();
  ::PB_AVAP_Speedbump* mutable_aspeedbump(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PB_AVAP_Speedbump >*
      mutable_aspeedbump();
  private:
  const ::PB_AVAP_Speedbump& _internal_aspeedbump(int index) const;
  ::PB_AVAP_Speedbump* _internal_add_aspeedbump();
  public:
  const ::PB_AVAP_Speedbump& aspeedbump(int index) const;
  ::PB_AVAP_Speedbump* add_aspeedbump();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PB_AVAP_Speedbump >&
      aspeedbump() const;

  // uint64 TimeMsec = 1;
  void clear_timemsec();
  ::PROTOBUF_NAMESPACE_ID::uint64 timemsec() const;
  void set_timemsec(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_timemsec() const;
  void _internal_set_timemsec(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // @@protoc_insertion_point(class_scope:PB_OdInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PB_AVAP_StcBarrier > astcbarrier_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PB_AVAP_DynBarrier > adynbarrier_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PB_AVAP_Speedbump > aspeedbump_;
  ::PROTOBUF_NAMESPACE_ID::uint64 timemsec_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_hmi_5f3d_2fmv_5fod_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PB_AVAP_StcBarrier

// uint32 AVAP_StcBarrierType = 1;
inline void PB_AVAP_StcBarrier::clear_avap_stcbarriertype() {
  avap_stcbarriertype_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 PB_AVAP_StcBarrier::_internal_avap_stcbarriertype() const {
  return avap_stcbarriertype_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 PB_AVAP_StcBarrier::avap_stcbarriertype() const {
  // @@protoc_insertion_point(field_get:PB_AVAP_StcBarrier.AVAP_StcBarrierType)
  return _internal_avap_stcbarriertype();
}
inline void PB_AVAP_StcBarrier::_internal_set_avap_stcbarriertype(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  avap_stcbarriertype_ = value;
}
inline void PB_AVAP_StcBarrier::set_avap_stcbarriertype(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_avap_stcbarriertype(value);
  // @@protoc_insertion_point(field_set:PB_AVAP_StcBarrier.AVAP_StcBarrierType)
}

// float AVAP_StcBarrier_X = 2;
inline void PB_AVAP_StcBarrier::clear_avap_stcbarrier_x() {
  avap_stcbarrier_x_ = 0;
}
inline float PB_AVAP_StcBarrier::_internal_avap_stcbarrier_x() const {
  return avap_stcbarrier_x_;
}
inline float PB_AVAP_StcBarrier::avap_stcbarrier_x() const {
  // @@protoc_insertion_point(field_get:PB_AVAP_StcBarrier.AVAP_StcBarrier_X)
  return _internal_avap_stcbarrier_x();
}
inline void PB_AVAP_StcBarrier::_internal_set_avap_stcbarrier_x(float value) {
  
  avap_stcbarrier_x_ = value;
}
inline void PB_AVAP_StcBarrier::set_avap_stcbarrier_x(float value) {
  _internal_set_avap_stcbarrier_x(value);
  // @@protoc_insertion_point(field_set:PB_AVAP_StcBarrier.AVAP_StcBarrier_X)
}

// float AVAP_StcBarrier_Y = 3;
inline void PB_AVAP_StcBarrier::clear_avap_stcbarrier_y() {
  avap_stcbarrier_y_ = 0;
}
inline float PB_AVAP_StcBarrier::_internal_avap_stcbarrier_y() const {
  return avap_stcbarrier_y_;
}
inline float PB_AVAP_StcBarrier::avap_stcbarrier_y() const {
  // @@protoc_insertion_point(field_get:PB_AVAP_StcBarrier.AVAP_StcBarrier_Y)
  return _internal_avap_stcbarrier_y();
}
inline void PB_AVAP_StcBarrier::_internal_set_avap_stcbarrier_y(float value) {
  
  avap_stcbarrier_y_ = value;
}
inline void PB_AVAP_StcBarrier::set_avap_stcbarrier_y(float value) {
  _internal_set_avap_stcbarrier_y(value);
  // @@protoc_insertion_point(field_set:PB_AVAP_StcBarrier.AVAP_StcBarrier_Y)
}

// uint32 AVAP_StcBarrierDrct = 4;
inline void PB_AVAP_StcBarrier::clear_avap_stcbarrierdrct() {
  avap_stcbarrierdrct_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 PB_AVAP_StcBarrier::_internal_avap_stcbarrierdrct() const {
  return avap_stcbarrierdrct_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 PB_AVAP_StcBarrier::avap_stcbarrierdrct() const {
  // @@protoc_insertion_point(field_get:PB_AVAP_StcBarrier.AVAP_StcBarrierDrct)
  return _internal_avap_stcbarrierdrct();
}
inline void PB_AVAP_StcBarrier::_internal_set_avap_stcbarrierdrct(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  avap_stcbarrierdrct_ = value;
}
inline void PB_AVAP_StcBarrier::set_avap_stcbarrierdrct(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_avap_stcbarrierdrct(value);
  // @@protoc_insertion_point(field_set:PB_AVAP_StcBarrier.AVAP_StcBarrierDrct)
}

// -------------------------------------------------------------------

// PB_AVAP_DynBarrier

// uint32 AVAP_DynBarrierType = 1;
inline void PB_AVAP_DynBarrier::clear_avap_dynbarriertype() {
  avap_dynbarriertype_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 PB_AVAP_DynBarrier::_internal_avap_dynbarriertype() const {
  return avap_dynbarriertype_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 PB_AVAP_DynBarrier::avap_dynbarriertype() const {
  // @@protoc_insertion_point(field_get:PB_AVAP_DynBarrier.AVAP_DynBarrierType)
  return _internal_avap_dynbarriertype();
}
inline void PB_AVAP_DynBarrier::_internal_set_avap_dynbarriertype(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  avap_dynbarriertype_ = value;
}
inline void PB_AVAP_DynBarrier::set_avap_dynbarriertype(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_avap_dynbarriertype(value);
  // @@protoc_insertion_point(field_set:PB_AVAP_DynBarrier.AVAP_DynBarrierType)
}

// float AVAP_DynBarrier_X = 2;
inline void PB_AVAP_DynBarrier::clear_avap_dynbarrier_x() {
  avap_dynbarrier_x_ = 0;
}
inline float PB_AVAP_DynBarrier::_internal_avap_dynbarrier_x() const {
  return avap_dynbarrier_x_;
}
inline float PB_AVAP_DynBarrier::avap_dynbarrier_x() const {
  // @@protoc_insertion_point(field_get:PB_AVAP_DynBarrier.AVAP_DynBarrier_X)
  return _internal_avap_dynbarrier_x();
}
inline void PB_AVAP_DynBarrier::_internal_set_avap_dynbarrier_x(float value) {
  
  avap_dynbarrier_x_ = value;
}
inline void PB_AVAP_DynBarrier::set_avap_dynbarrier_x(float value) {
  _internal_set_avap_dynbarrier_x(value);
  // @@protoc_insertion_point(field_set:PB_AVAP_DynBarrier.AVAP_DynBarrier_X)
}

// float AVAP_DynBarrier_Y = 3;
inline void PB_AVAP_DynBarrier::clear_avap_dynbarrier_y() {
  avap_dynbarrier_y_ = 0;
}
inline float PB_AVAP_DynBarrier::_internal_avap_dynbarrier_y() const {
  return avap_dynbarrier_y_;
}
inline float PB_AVAP_DynBarrier::avap_dynbarrier_y() const {
  // @@protoc_insertion_point(field_get:PB_AVAP_DynBarrier.AVAP_DynBarrier_Y)
  return _internal_avap_dynbarrier_y();
}
inline void PB_AVAP_DynBarrier::_internal_set_avap_dynbarrier_y(float value) {
  
  avap_dynbarrier_y_ = value;
}
inline void PB_AVAP_DynBarrier::set_avap_dynbarrier_y(float value) {
  _internal_set_avap_dynbarrier_y(value);
  // @@protoc_insertion_point(field_set:PB_AVAP_DynBarrier.AVAP_DynBarrier_Y)
}

// uint32 AVAP_DynBarrierDrct = 4;
inline void PB_AVAP_DynBarrier::clear_avap_dynbarrierdrct() {
  avap_dynbarrierdrct_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 PB_AVAP_DynBarrier::_internal_avap_dynbarrierdrct() const {
  return avap_dynbarrierdrct_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 PB_AVAP_DynBarrier::avap_dynbarrierdrct() const {
  // @@protoc_insertion_point(field_get:PB_AVAP_DynBarrier.AVAP_DynBarrierDrct)
  return _internal_avap_dynbarrierdrct();
}
inline void PB_AVAP_DynBarrier::_internal_set_avap_dynbarrierdrct(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  avap_dynbarrierdrct_ = value;
}
inline void PB_AVAP_DynBarrier::set_avap_dynbarrierdrct(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_avap_dynbarrierdrct(value);
  // @@protoc_insertion_point(field_set:PB_AVAP_DynBarrier.AVAP_DynBarrierDrct)
}

// -------------------------------------------------------------------

// PB_AVAP_Speedbump

// float AVAP_Speedbump_A_X = 1;
inline void PB_AVAP_Speedbump::clear_avap_speedbump_a_x() {
  avap_speedbump_a_x_ = 0;
}
inline float PB_AVAP_Speedbump::_internal_avap_speedbump_a_x() const {
  return avap_speedbump_a_x_;
}
inline float PB_AVAP_Speedbump::avap_speedbump_a_x() const {
  // @@protoc_insertion_point(field_get:PB_AVAP_Speedbump.AVAP_Speedbump_A_X)
  return _internal_avap_speedbump_a_x();
}
inline void PB_AVAP_Speedbump::_internal_set_avap_speedbump_a_x(float value) {
  
  avap_speedbump_a_x_ = value;
}
inline void PB_AVAP_Speedbump::set_avap_speedbump_a_x(float value) {
  _internal_set_avap_speedbump_a_x(value);
  // @@protoc_insertion_point(field_set:PB_AVAP_Speedbump.AVAP_Speedbump_A_X)
}

// float AVAP_Speedbump_A_Y = 2;
inline void PB_AVAP_Speedbump::clear_avap_speedbump_a_y() {
  avap_speedbump_a_y_ = 0;
}
inline float PB_AVAP_Speedbump::_internal_avap_speedbump_a_y() const {
  return avap_speedbump_a_y_;
}
inline float PB_AVAP_Speedbump::avap_speedbump_a_y() const {
  // @@protoc_insertion_point(field_get:PB_AVAP_Speedbump.AVAP_Speedbump_A_Y)
  return _internal_avap_speedbump_a_y();
}
inline void PB_AVAP_Speedbump::_internal_set_avap_speedbump_a_y(float value) {
  
  avap_speedbump_a_y_ = value;
}
inline void PB_AVAP_Speedbump::set_avap_speedbump_a_y(float value) {
  _internal_set_avap_speedbump_a_y(value);
  // @@protoc_insertion_point(field_set:PB_AVAP_Speedbump.AVAP_Speedbump_A_Y)
}

// float AVAP_Speedbump_B_X = 3;
inline void PB_AVAP_Speedbump::clear_avap_speedbump_b_x() {
  avap_speedbump_b_x_ = 0;
}
inline float PB_AVAP_Speedbump::_internal_avap_speedbump_b_x() const {
  return avap_speedbump_b_x_;
}
inline float PB_AVAP_Speedbump::avap_speedbump_b_x() const {
  // @@protoc_insertion_point(field_get:PB_AVAP_Speedbump.AVAP_Speedbump_B_X)
  return _internal_avap_speedbump_b_x();
}
inline void PB_AVAP_Speedbump::_internal_set_avap_speedbump_b_x(float value) {
  
  avap_speedbump_b_x_ = value;
}
inline void PB_AVAP_Speedbump::set_avap_speedbump_b_x(float value) {
  _internal_set_avap_speedbump_b_x(value);
  // @@protoc_insertion_point(field_set:PB_AVAP_Speedbump.AVAP_Speedbump_B_X)
}

// float AVAP_Speedbump_B_Y = 4;
inline void PB_AVAP_Speedbump::clear_avap_speedbump_b_y() {
  avap_speedbump_b_y_ = 0;
}
inline float PB_AVAP_Speedbump::_internal_avap_speedbump_b_y() const {
  return avap_speedbump_b_y_;
}
inline float PB_AVAP_Speedbump::avap_speedbump_b_y() const {
  // @@protoc_insertion_point(field_get:PB_AVAP_Speedbump.AVAP_Speedbump_B_Y)
  return _internal_avap_speedbump_b_y();
}
inline void PB_AVAP_Speedbump::_internal_set_avap_speedbump_b_y(float value) {
  
  avap_speedbump_b_y_ = value;
}
inline void PB_AVAP_Speedbump::set_avap_speedbump_b_y(float value) {
  _internal_set_avap_speedbump_b_y(value);
  // @@protoc_insertion_point(field_set:PB_AVAP_Speedbump.AVAP_Speedbump_B_Y)
}

// -------------------------------------------------------------------

// PB_OdInfo

// uint64 TimeMsec = 1;
inline void PB_OdInfo::clear_timemsec() {
  timemsec_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 PB_OdInfo::_internal_timemsec() const {
  return timemsec_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 PB_OdInfo::timemsec() const {
  // @@protoc_insertion_point(field_get:PB_OdInfo.TimeMsec)
  return _internal_timemsec();
}
inline void PB_OdInfo::_internal_set_timemsec(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  timemsec_ = value;
}
inline void PB_OdInfo::set_timemsec(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_timemsec(value);
  // @@protoc_insertion_point(field_set:PB_OdInfo.TimeMsec)
}

// repeated .PB_AVAP_StcBarrier aStcBarrier = 2;
inline int PB_OdInfo::_internal_astcbarrier_size() const {
  return astcbarrier_.size();
}
inline int PB_OdInfo::astcbarrier_size() const {
  return _internal_astcbarrier_size();
}
inline void PB_OdInfo::clear_astcbarrier() {
  astcbarrier_.Clear();
}
inline ::PB_AVAP_StcBarrier* PB_OdInfo::mutable_astcbarrier(int index) {
  // @@protoc_insertion_point(field_mutable:PB_OdInfo.aStcBarrier)
  return astcbarrier_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PB_AVAP_StcBarrier >*
PB_OdInfo::mutable_astcbarrier() {
  // @@protoc_insertion_point(field_mutable_list:PB_OdInfo.aStcBarrier)
  return &astcbarrier_;
}
inline const ::PB_AVAP_StcBarrier& PB_OdInfo::_internal_astcbarrier(int index) const {
  return astcbarrier_.Get(index);
}
inline const ::PB_AVAP_StcBarrier& PB_OdInfo::astcbarrier(int index) const {
  // @@protoc_insertion_point(field_get:PB_OdInfo.aStcBarrier)
  return _internal_astcbarrier(index);
}
inline ::PB_AVAP_StcBarrier* PB_OdInfo::_internal_add_astcbarrier() {
  return astcbarrier_.Add();
}
inline ::PB_AVAP_StcBarrier* PB_OdInfo::add_astcbarrier() {
  // @@protoc_insertion_point(field_add:PB_OdInfo.aStcBarrier)
  return _internal_add_astcbarrier();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PB_AVAP_StcBarrier >&
PB_OdInfo::astcbarrier() const {
  // @@protoc_insertion_point(field_list:PB_OdInfo.aStcBarrier)
  return astcbarrier_;
}

// repeated .PB_AVAP_DynBarrier aDynBarrier = 3;
inline int PB_OdInfo::_internal_adynbarrier_size() const {
  return adynbarrier_.size();
}
inline int PB_OdInfo::adynbarrier_size() const {
  return _internal_adynbarrier_size();
}
inline void PB_OdInfo::clear_adynbarrier() {
  adynbarrier_.Clear();
}
inline ::PB_AVAP_DynBarrier* PB_OdInfo::mutable_adynbarrier(int index) {
  // @@protoc_insertion_point(field_mutable:PB_OdInfo.aDynBarrier)
  return adynbarrier_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PB_AVAP_DynBarrier >*
PB_OdInfo::mutable_adynbarrier() {
  // @@protoc_insertion_point(field_mutable_list:PB_OdInfo.aDynBarrier)
  return &adynbarrier_;
}
inline const ::PB_AVAP_DynBarrier& PB_OdInfo::_internal_adynbarrier(int index) const {
  return adynbarrier_.Get(index);
}
inline const ::PB_AVAP_DynBarrier& PB_OdInfo::adynbarrier(int index) const {
  // @@protoc_insertion_point(field_get:PB_OdInfo.aDynBarrier)
  return _internal_adynbarrier(index);
}
inline ::PB_AVAP_DynBarrier* PB_OdInfo::_internal_add_adynbarrier() {
  return adynbarrier_.Add();
}
inline ::PB_AVAP_DynBarrier* PB_OdInfo::add_adynbarrier() {
  // @@protoc_insertion_point(field_add:PB_OdInfo.aDynBarrier)
  return _internal_add_adynbarrier();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PB_AVAP_DynBarrier >&
PB_OdInfo::adynbarrier() const {
  // @@protoc_insertion_point(field_list:PB_OdInfo.aDynBarrier)
  return adynbarrier_;
}

// repeated .PB_AVAP_Speedbump aSpeedbump = 4;
inline int PB_OdInfo::_internal_aspeedbump_size() const {
  return aspeedbump_.size();
}
inline int PB_OdInfo::aspeedbump_size() const {
  return _internal_aspeedbump_size();
}
inline void PB_OdInfo::clear_aspeedbump() {
  aspeedbump_.Clear();
}
inline ::PB_AVAP_Speedbump* PB_OdInfo::mutable_aspeedbump(int index) {
  // @@protoc_insertion_point(field_mutable:PB_OdInfo.aSpeedbump)
  return aspeedbump_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PB_AVAP_Speedbump >*
PB_OdInfo::mutable_aspeedbump() {
  // @@protoc_insertion_point(field_mutable_list:PB_OdInfo.aSpeedbump)
  return &aspeedbump_;
}
inline const ::PB_AVAP_Speedbump& PB_OdInfo::_internal_aspeedbump(int index) const {
  return aspeedbump_.Get(index);
}
inline const ::PB_AVAP_Speedbump& PB_OdInfo::aspeedbump(int index) const {
  // @@protoc_insertion_point(field_get:PB_OdInfo.aSpeedbump)
  return _internal_aspeedbump(index);
}
inline ::PB_AVAP_Speedbump* PB_OdInfo::_internal_add_aspeedbump() {
  return aspeedbump_.Add();
}
inline ::PB_AVAP_Speedbump* PB_OdInfo::add_aspeedbump() {
  // @@protoc_insertion_point(field_add:PB_OdInfo.aSpeedbump)
  return _internal_add_aspeedbump();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PB_AVAP_Speedbump >&
PB_OdInfo::aspeedbump() const {
  // @@protoc_insertion_point(field_list:PB_OdInfo.aSpeedbump)
  return aspeedbump_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_hmi_5f3d_2fmv_5fod_2eproto
